# Generated by Django 4.1.13 on 2024-03-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='applicants',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
