# Generated by Django 5.0.2 on 2024-02-15 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=50)),
                ('photo_project', models.ImageField(upload_to='photos_projects/')),
                ('description', models.TextField()),
                ('num_events', models.IntegerField(default=0)),
                ('num_integrants', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('instruments', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=200)),
                ('years', models.IntegerField(default=0)),
                ('photo', models.ImageField(upload_to='photos_users/')),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=50)),
            ],
        ),
    ]
