# Generated by Django 4.1.13 on 2024-04-21 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_graph_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='graph',
        ),
    ]
