# Generated by Django 4.1.13 on 2024-05-16 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_user_name_user_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bands',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
