# Generated by Django 4.1.13 on 2024-04-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=250)),
                ('genre', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=10)),
                ('img', models.ImageField(upload_to='groups/images/')),
            ],
        ),
    ]
